// Secció B: Dret Constitucional i Estatut d'Autonomia
export const seccioB = {
  "0": { // B.1: EAC - Estatut d'Autonomia de Catalunya
    "0": "1. Antecedents històrics i naturalesa jurídica\n\nLa voluntat d’autogovern de Catalunya s’ha manifestat històricament en l’existència d’institucions pròpies, com la Generalitat, que té el seu origen en les Corts medievals. En l’època contemporània, després de la pèrdua de les institucions el 1714, la Mancomunitat de Catalunya (1914-1923) va significar el primer pas cap a la recuperació de l’autonomia.\n\nDurant la Segona República es va aprovar l’Estatut de Núria (1932), el primer estatut d’autonomia formal, que va ser derogat pel franquisme l’any 1938. Amb la recuperació de la democràcia, es va aprovar l’Estatut de Sau (1979), que va regir la vida política catalana durant més de vint-i-cinc anys fins a l’aprovació del nou Estatut d’Autonomia de Catalunya de 2006 (Llei Orgànica 6/2006, de 19 de juliol).\n\nL’Estatut d’Autonomia és la norma institucional bàsica de Catalunya, tal com preveu la Constitució espanyola (Art. 147 CE). Té una naturalesa jurídica doble: d’una banda, és la llei fonamental de Catalunya; de l’altra, és una llei orgànica de l’Estat, que forma part del bloc de la constitucionalitat.",
    "1": "2. Contingut i estructura\n\nL’Estatut d'Autonomia de 2006 és un text ampli i detallat que busca blindar l'autogovern i definir els drets de la ciutadania. S'estructura en un Preàmbul, un Títol Preliminar i set títols més, amb un total de 223 articles.\n\n- Títol Preliminar: Defineix Catalunya com a nacionalitat, els símbols, la llengua pròpia i la seu de la Generalitat.\n- Títol I: Drets, deures i principis rectors.\n- Títol II: Les institucions de la Generalitat (Parlament, President, Govern).\n- Títol III: Del Poder Judicial a Catalunya.\n- Títol IV: De les competències.\n- Títol V: De les relacions amb l'Estat i amb la Unió Europea.\n- Títol VI: Del finançament de la Generalitat.\n- Títol VII: De la reforma de l'Estatut.",
    "2": "3. Els drets, els deures i els principis rectors\n\nL’Estatut de 2006 inclou un catàleg propi de drets i deures que vinculen a tots els poders públics de Catalunya. Aquests es divideixen en àmbits:\n\n- Drets en l’àmbit civil i social: Dret a la dignitat de la persona, protecció de la família, dret a viure en un medi ambient sa.\n- Drets lingüístics: Dret a utilitzar el català i el castellà. Dret a ser atès en català en l’administració i la justícia.\n- Drets educatius i culturals.\n\nEls principis rectors són orientacions que han de guiar les polítiques públiques de la Generalitat en matèria d’igualtat, habitatge, recerca i protecció social.",
    "3": "4. Les competències de la Generalitat de Catalunya\n\nL’Estatut defineix tres tipus principals de competències:\n\n- Competències exclusives: La Generalitat té tota la potestat legislativa, reglamentària i executiva (ex: cultura, turisme, dret civil català).\n- Competències compartides: L’Estat estableix les bases i la Generalitat té la potestat legislativa de desplegament i executiva (ex: sanitat, medi ambient).\n- Competències executives: L’Estat té la potestat legislativa i la Generalitat té la funció executiva, és a dir, la gestió administrativa (ex: treball).",
    "4": "5. La competència en matèria de seguretat pública\n\nL’Article 164 de l’Estatut estableix que correspon a la Generalitat la planificació i la gestió del sistema de seguretat pública de Catalunya. Això inclou la creació, organització i comandament ordinari dels Mossos d’Esquadra, la coordinació de les policies locals i la protecció civil.\n\nL’Estat manté la competència en matèria de seguretat pública d’àmbit estatal (control de fronteres, estrangeria, terrorisme). Per coordinar-se existeix la Junta de Seguretat de Catalunya."
  },
  "1": { // B.2: Les institucions polítiques de Catalunya
    "0": "1. La Generalitat de Catalunya\n\nLa Generalitat és el sistema institucional en què s'organitza políticament l'autogovern de Catalunya. Està integrada pel Parlament, la Presidència de la Generalitat, el Govern i les altres institucions que estableix l'Estatut (Art. 2 EAC).",
    "1": "2. El Parlament de Catalunya\n\nRepresenta el poble de Catalunya, exerceix la potestat legislativa, aprova el pressupost i controla l’acció del Govern. Està format per 135 diputats elegits cada quatre anys.\n\nEls òrgans principals són:\n- El President del Parlament.\n- La Mesa: Òrgan rector.\n- El Ple: Assemblea de tots els diputats.\n- Les Comissions: Treball especialitzat.\n- La Diputació Permanent: Vetlla pels poders quan el Parlament no està reunit.",
    "2": "3. La Presidència de la Generalitat de Catalunya\n\nEl President de la Generalitat és la més alta representació de la Generalitat i l’ordinària de l’Estat a Catalunya. Dirigeix i coordina l’acció del Govern.\n\nÉs elegit pel Parlament d’entre els seus membres i és nomenat pel Rei. Té la responsabilitat de nomenar i destituir els consellers i és responsable políticament davant del Parlament.",
    "3": "4. El Govern i l'Administració de la Generalitat de Catalunya\n\nEl Govern és l’òrgan superior col·legiat que dirigeix la política i l’administració de la Generalitat. Exerceix la funció executiva i la potestat reglamentària.\n\nEstà compost pel President, el Conseller Primer (si s'escau) i els Consellers. Les seves deliberacions són secretes i respon de forma solidària davant el Parlament.",
    "4": "5. Altres institucions estatutàries\n\n- Consell de Garanties Estatutàries: Vetlla per l'adequació de les lleis a l'Estatut i la Constitució.\n- Síndic de Greuges: Defensa els drets i llibertats ciutadanes davant l'Administració.\n- Sindicatura de Comptes: Fiscalitza els comptes del sector públic.\n- Consell de l’Audiovisual de Catalunya (CAC): Regula el sector radiofònic i televisiu."
  },
  "2": { // B.3: L'ordenament jurídic de l'Estat
    "0": "1. L'ordenament jurídic\n\nÉs el conjunt organitzat de normes que regeixen en un territori. Es basa en els principis de jerarquia normativa (l'article 9.3 CE), legalitat, seguretat jurídica i irretroactivitat de les disposicions sancionadores no favorables.",
    "1": "2. La Constitució Espanyola de 1978\n\nÉs la norma suprema de l’Estat. Defineix Espanya com un Estat social i democràtic de dret, amb la monarquia parlamentària com a forma política. Es divideix en un Títol Preliminar i deu títols més.",
    "2": "3. La llei\n\nNorma escrita, general i obligatòria dictada pel poder legislatiu. Hi ha lleis orgàniques (majoria absoluta per a drets fonamentals, estatuts, etc.) i lleis ordinàries (majoria simple).",
    "3": "4. Les normes amb rang de llei\n\nNormes dictades pel Govern amb el mateix rang que una llei:\n- Reial Decret Llei: Per casos d'extraordinària i urgent necessitat.\n- Reial Decret Legislatiu: Per delegació de les Corts al Govern (Textos refosos o articulats).",
    "4": "5. El Reglament\n\nNorma de rang inferior a la llei dictada per l'Administració. Serveix per desplegar i detallar el contingut de les lleis (Decrets, Ordres).",
    "5": "6. Els tractats internacionals\n\nAcords subscrits per l'Estat amb altres estats o organismes internacionals. Un cop publicats oficialment (BOE), formen part de l'ordenament jurídic intern."
  }
};
